config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :businesses
  get 'home/about'
  # root 'home#index'
  root 'businesses#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :businesses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [ :show, :edit, :update, :destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /businesses or /businesses.json
  def index
    @businesses = Business.all
  end

  # GET /businesses/1 or /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    # @business = Business.new
    @business = current_user.businesses.build
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses or /businesses.json
  def create
    # @business = Business.new(business_params)
    @business = current_user.businesses.build(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: "new entry saved" }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1 or /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: "update successful" }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1 or /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: "record deleted" }
      format.json { head :no_content }
    end
  end

# to route to assign current user to active user
  
  def correct_user
    @business = current_user.businesses.find_by(id: params[:id])
    redirect_to businesses_path, notice: "Not an authorized action." if @business.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def business_params
      params.require(:business).permit(:business_name, :website, :social_media, :email, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def about
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/businesses/_form.html.erb
<%= form_with(model: business) do |form| %>
  <% if business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
        <% business.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :business_name, class:"form-control", placeholder:"Business Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :social_media, class:"form-control", placeholder:"Social Media: example IG @Bk2Mi" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :website, class:"form-control", placeholder:"Website" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_id, id: :business_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-secondary"%>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing Business</h1>
<br>
<%= render 'form', business: @business %>
<br>
<%= link_to 'Show', @business, class: "btn btn-secondary" %>  
<%= link_to 'Delete', @business, method: :delete, data: { confirm: 'Once deleted this action can not be undone.' }, class: "btn btn-danger" %> 
<%= link_to 'Back', businesses_path, class: "btn btn-secondary" %>

app/views/businesses/index.html.erb
<% if user_signed_in? %>

<caption><h1>Network</h1></caption>

<table class="table table-striped table-hover table-bordered caption-top">
  <thead class="thead-dark">
    <tr>
      <th>Business name</th>
      <th>Website</th>
      <th>Social media</th>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
    <!-- the if statement is to only show current user entries to current user -->
      <% if business.user == current_user %>
      <tr>
        <td><%= link_to business.business_name, business %></td>
        <td><%= business.website %></td>
        <td><%= business.social_media %></td>
        <td><%= business.email %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add My Business', new_business_path, class: "btn btn-secondary" %>


<% else %>

<h1>Hello world</h1>

<% end %>

app/views/businesses/new.html.erb
<h1>My Network</h1>
<br>
<%= render 'form', business: @business %>
<br>
<%= link_to 'Back', businesses_path, class: "btn btn-success" %>

app/views/businesses/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4"><%= @business.business_name %></h1>
  <p>
  <strong>Website:</strong>
  <%= @business.website %> | 
  <strong>Social media:</strong>
  <%= @business.social_media %> |
  <strong>Email:</strong>
  <%= @business.email %>
</p>
</p>
<br>
    <%= link_to 'Edit', edit_business_path(@business), class: "btn btn-dark" %> 
    <%= link_to 'Delete', @business, method: :delete, data: { confirm: 'Once deleted this action can not be undone.' }, class: "btn btn-danger" %> 
    <%= link_to 'Back', businesses_path, class: "btn btn-success" %>
  </div>
</div>

app/views/home/_footer.html.erb
<div>
        <a class="footer-link" href="https://twitter.com/rynetwork">Twitter</a> <span> | </span>
        <a class="footer-link" href="https://www.linkedin.com/in/susie-newton-31bb3360/">LinkedIn</a>
    
  <br> 

  <script>
        © 2008 new Date().getFullYear() > 2010 && document.write("- " + new Date().getFullYear());
      </script> S. E. Newton all rights reserved and managed by <br>
      <p>RYBNetWork</p><br />

      <a href="https://app.termly.io/document/terms-of-use-for-website/cb49b42f-caca-4d7d-b413-985ac0070b58"> Terms and Service</a>
      | <a href="https://app.termly.io/document/privacy-policy/a21e1e7d-3e66-469c-ae47-46aea44a9a8e">Privacy Policy</a> |
      <a href="https://app.termly.io/document/cookie-policy/e0702946-d189-41ef-b200-53ba4236b618">Cookies Policy</a>
    
    <br>
  </center>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%= link_to "My Network", root_path, class:"navbar-brand" %>
    
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
 
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        
        <li class="nav-item">
          <%= link_to "About Me", home_about_path, class:"nav-link" %>
        </li>
        
    <% if user_signed_in? %>
         
         <li class="nav-item">
          <%= link_to "Enhance My Network", new_business_path, class:"nav-link" %>
        </li>

         <li class="nav-item">
           <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
         </li>

         <li class="nav-item">
           <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
         </li>

    <% else %>

        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>

         <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>

    <% end %>

    </ul>

        <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<!DOCTYPE html>
<html>
<head>
	<title> Susie Newton </title>
</head>
<body>
<div class="container">
  <h1>About Me</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr>
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <p class="lead">
    <a class="btn btn-outline-danger btn-md" href="#" role="button">Learn more</a>
  </p>
</div>
</body>
</html>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Hello, world!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </p>
</div>

app/views/layouts/_alerts_html.erb
<div class="card">
  
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
  	<%= notice %>  
    <div class="card-body">
     <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>  
  </div>
</div>  

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
 <script>
  (function() {
    var s = document.createElement('script');
    s.type = 'text/javascript';
    s.async = true;
    s.src = 'https://app.termly.io/embed.min.js';
    s.id = '5b79eab9-04b9-4df7-b5f5-44530c0cbced';
    s.setAttribute("data-name", "termly-embed-banner");
    var x = document.getElementsByTagName('script')[0];
    x.parentNode.insertBefore(s, x);
  })();
</script>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="keywords" content="">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
      <link rel="icon" href="rybnetwork_susienewton.jpg">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

      <title>RYBNetWork</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
 
  </head>
  <body>
     
    <%= render "home/header" %>
    
    <div class="container">
   <br>
     <% if notice %>     
     <%= render 'layouts/alerts_html.erb' %> 
     <% end %>

     <%= yield %>

    </div>

    <br>
    <br>
    <br>
<footer>
   
   <center>

  <%= render "home/footer" %>
   
   <center>
    
  </footer>
  </body>
</html>